services:
  - type: web
    name: lifetracker-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGO_URI
        sync: false        # set manually in Render dashboard
      - key: JWT_SECRET
        sync: false        # set manually in Render dashboard
